zookeeper3:
  image: wurstmeister/zookeeper
  hostname: zoo3
  extra_hosts:
    - "zoo1:10.10.180.83"
    - "zoo2:10.10.180.84"
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"

  environment:  
    zk_id: 3
    # Do 0.0.0.0 for the current Zk server that you are configuring, 
    # using the Public IP wont help to form the Quorum
    zk_server.1: 10.10.180.83:2888:3888
    zk_server.2: 10.10.180.84:2888:3888 
    zk_server.3: 0.0.0.0:2888:3888


kafka3:
  image: wurstmeister/kafka
  container_name: kafka3
  ports:
    - "9092:9092"
  environment:
    KAFKA_BROKER_ID: 3
    KAFKA_ADVERTISED_HOST_NAME: 10.10.180.82
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_ZOOKEEPER_CONNECT: 10.10.180.83:2181,10.10.180.84:2181,10.10.180.82:2181

  volumes:
    - /tmp/docker/kafka3/logs:/logs
    - /tmp/docker/kafka3/data:/data
