zookeeper2:
  image: confluent/zookeeper
  hostname: zoo2
  extra_hosts:
    - "zoo1:10.9.37.231"
    - "zoo3:10.9.38.205"
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"

  environment:  
    zk_id: 2
    # Do 0.0.0.0 for the current Zk server that you are configuring, 
    # using the Public IP wont help to form the Quorum
    zk_server.1=10.9.37.231:2888:3888
    zk_server.2=0.0.0.0:2888:3888 
    zk_server.3=10.9.38.205:2888:3888


kafka2:
  image: confluent/kafka
  container_name: kafka2
  ports:
    - "9092:9092"
  environment:
    KAFKA_BROKER_ID: 2
    KAFKA_ADVERTISED_HOST_NAME: 10.9.38.56
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_ZOOKEEPER_CONNECT: 10.9.37.231:2181,10.9.38.56:2181,10.9.38.205:2181

  volumes:
    - /tmp/docker/kafka2/logs:/logs
    - /tmp/docker/kafka2/data:/data

restproxy2:
  image: confluent/rest-proxy
  container_name: restproxy2
  ports:
    - "8082:8082"
  environment:
    REST_PROXY_ID: 2
    # This can either connect to just the current host / a quorum
    # quorum is better for node notification one a node goes down
    RP_ZOOKEEPER_CONNECT: 10.9.37.231:2181,10.9.38.56:2181,10.9.38.205:2181    
